# Add your own tasks in files placed in lib/tasks ending in .rake,
# for example lib/tasks/capistrano.rake, and they will automatically be available to Rake.

require_relative 'config/application'

Rails.application.load_tasks

desc 'rake task that runs sudo service postgresql start'
task :start_psql do
  system('sudo service postgresql start')
end

desc 'rake task that runs sudo service postgresql stop'
task :stop_psql do
  system('sudo service postgresql stop')
end
